server:
  port: 8761

spring:
  application:
    name: AurudaDiscovery #??? ID

eureka:
  client:
    allow-redirects: false #default : true
    fetch-registry: false #default : true

# Eureka Libray? ????? ??? ????? Eureka Client?? ???? ???? ??? ???????.
# ??? true? ???? ?? ??? ??? ???? ???? ???? ??? ?? ????? false? ?? ?????.